# Setup
title:        The Analog
tagline:      Analog tools in a digital age
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       The Analog
  url:        http://www.the-analog.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown