# Setup
title:        Golana.net
tagline:      Analog tools in a digital age
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Golana
  url:        http://www.golana.net

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown